version: '3'

services:
  nginx:
    container_name: nginx
    image: staticfloat/nginx-certbot
    restart: "always"
    ports:
      - 80:80
      - 443:443
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      - CERTBOT_EMAIL
      - STAGING=0
      - RENEWAL_INTERVAL=30d
    volumes:
      - letsencrypt-data:/etc/letsencrypt
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - ./supported_domains:/etc/certbot/extra_domains:ro
    networks:
      - webserver-net

volumes:
  letsencrypt-data:

networks:
  webserver-net:
    driver: bridge
