version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: "always"
    ports:
      - 80:80
      - 443:443
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - webserver-net

networks:
  webserver-net:
    driver: bridge
